perf changes issue

diff --git a/shellpacks/shellpack-bench-iperf3 b/shellpacks/shellpack-bench-iperf3
--- a/shellpacks/shellpack-bench-iperf3
+++ b/shellpacks/shellpack-bench-iperf3
@@ -230,6 +230,20 @@ for NR_THREADS in $THREADS; do
 	eval $TASKSET_CLIENT $IPERFROOT/bin/iperf3 $IPERF3_OPTS \
 			2>&1 > $LOGDIR_RESULTS/$IPERF_PROTOCOL-$IPERF_MESSAGE_SIZE-$IPERF_MESSAGE_RATE-$NR_THREADS \
 			|| die "Failed to run iperf3"
+
+echo "iperf perf run starts "
+    	eval sh /mmtests/mmtests_CI/data_collection.sh 20 $LOGDIR_RESULTS $IPERF_PROTOCOL-$IPERF_MESSAGE_SIZE-$IPERF_MESSAGE_RATE-$NR_THREADS_perf &
+	eval date
+        IPERF3_OPTS="-c $SERVER_HOST \
+                $MSGSIZE_OPT $MSGRATE_OPT $SOCKETSIZE_OPT \
+                $PROTOCOL_OPT -t 100 \
+                -P $NR_THREADS --get-server-output -V"
+        echo $TASKSET_CLIENT "iperf3" $IPERF3_OPTS
+        monitor_pre_hook $LOGDIR_RESULTS $IPERF_PROTOCOL-$IPERF_MESSAGE_SIZE-$IPERF_MESSAGE_RATE-$NR_THREADS
+        eval $TASKSET_CLIENT $IPERFROOT/bin/iperf3 $IPERF3_OPTS \
+                        2>&1 > $LOGDIR_RESULTS/$IPERF_PROTOCOL-$IPERF_MESSAGE_SIZE-$IPERF_MESSAGE_RATE-$NR_THREADS_perf \
+                        || die "Failed to run iperf3"
+        eval date
 	monitor_post_hook $LOGDIR_RESULTS $IPERF_PROTOCOL-$IPERF_MESSAGE_SIZE-$IPERF_MESSAGE_RATE-$NR_THREADS
 	mmtests_server_ctl stop --serverside-name $IPERF_PROTOCOL-$IPERF_MESSAGE_SIZE-$IPERF_MESSAGE_RATE
 done
